### ISSUE TITLE
Daten puffern und gesammelt übertragen

### ISSUE THREAD

**Issue by chrissikay** [T-i-M-M-i/DE4LRoadTracker#14]
übertragen z.B.
- nach Beenden der Aufzeichnung
- bei vorhandener WLan-Verbindung
- manuell

**Comment by bastiion** [comment]
wird durch MQTT Library bereitgestellt. Puffergröße ist einstellbar (derzeit dennoch als konstante hart kodiert) Könnte bei Bedarf über Settings einstellbar gemacht werden.
